### ISSUE TITLE
Configuration is not proceeding to 'Choose Property' page

### ISSUE THREAD

**Issue by skybluesofa** [modmore/BigBrother#10]
First off, I'm installing this on a 2.2.6 site. That might be the problem. However, if not:

After copying and pasting the Authentication Code and then clicking the Verify button, I get a loading indicator and then nothing.

In the browser's developer console: I get this response from connector.php:
```
{"success":false,"message":"Unable to complete oAuth2 flow: <pre><\/pre>","total":0,"data":[],"object":[]}
```

Any ideas or suggestions?

**Comment by Mark-H** [comment]
If this problem still persists in a more recent version of MODX with the latest version of BigBrother, please feel free to reopen.
