### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by lanceC99** [modmore/BigBrother#112]
Hi, this might well not be an issues at all and just be linked with my miss configuring, but is anyone else running into this problem when authorizing with new custom OAuth creds recently.

Authorisation Error
Error 400: invalid_request
redirect_uri: urn:ietf:wg:oauth:2.0:oob

After looking around, i found this :
[https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#dates-oob]

Modx 3.01
Big Brother 2.2

**Comment by Mark-H** [comment]
They're indeed deprecating the "out of band" redirect uri, which we'll have to adapt big brother to [again].

Existing keys however are supposed to work until September/October, so you should still be able to use the default keys, or keys created a little while ago. 

I've updated the docs for using custom credentials to make note of this and will post updates here when I have them.

**Comment by lanceC99** [comment]
Yes, i confirm the default keys still work ok.
Great for the docs & the updates.
If i can be of any help, i'll post here too

**Comment by Mark-H** [comment]
I've almost got the update (3.0) ready to go. Will do a bit more maintenance work (updating dependencies) and such tomorrow and will then release a release candidate when it's ready.
