### ISSUE TITLE
Analytics Account setup leads to a missing Google website

### ISSUE THREAD

**Issue by gadgetto** [modmore/BigBrother#13]
Dont know since when this happens but about 2 months ago I could setup without problems.

**Comment by Mark-H** [comment]
Hm? Could you elaborate?

**Comment by gadgetto** [comment]
Step 1:
<img width="862" alt="screenshot 2015-11-09 13 09 53" src="https://cloud.githubusercontent.com/assets/876737/11033447/61f481c2-86e3-11e5-9fc7-b4b78de93f1a.png">

Step 2:
<img width="866" alt="screenshot 2015-11-09 13 10 18" src="https://cloud.githubusercontent.com/assets/876737/11033450/6ba3851a-86e3-11e5-9d54-49912befd547.png">

Step 3:
<img width="887" alt="screenshot 2015-11-09 13 10 43" src="https://cloud.githubusercontent.com/assets/876737/11033453/7afc8692-86e3-11e5-9b0e-581d900b3060.png">

The URL which leads to 404:
https://support.google.com/a/answer/6224347?p=oauth&rd=1

**Comment by mrhaw** [comment]
@gadgetto Try remove the extra fully and the re-install it. I believe I have seen this when signing in with the wrong google account.

**Comment by Mark-H** [comment]
I've not seen this myself, any further information would be very much welcome.

**Comment by gadgetto** [comment]
Couldn't reproduce since then. So issue can be closed.
