### ISSUE TITLE
Standalone Widgets in dashboard not loading data if main widget is missing

### ISSUE THREAD

**Issue by achterbahn** [modmore/BigBrother#159]
The standalone widgets only load data, if the main widget is placed in the dashboard, too. 
Otherwise the standalone widgets show, but do not load and show any data.

<img width="701" alt="image" src="https://github.com/modmore/BigBrother/assets/1411919/d8218407-64e0-4cf5-bb77-4c0f171bb392">

**Comment by muzzwood** [comment]
Thanks @achterbahn , this has been fixed and will be in the upcoming release.
