### ISSUE TITLE
Minor display bug in dashboard widget

### ISSUE THREAD

**Issue by ghost** [modmore/BigBrother#18]
The "visits" graph on the dashboard widget runs off the screen sometimes. 
![image](https://cloud.githubusercontent.com/assets/4050256/17559782/034a49b0-5ee5-11e6-90e4-aa3c56a023c0.png)

It doesn't happen every time but it's wrong more than it's right. It seems like if I haven't visited the dashboard in a while then when it first loads it displays correctly. After a refresh it though it will run off. When it happens, the height of the graph shrinks at the same time. Doesn't seem to be an issue on the CMP.

**Comment by iamdave210** [comment]
Happens in GC, FFx and IE10.

**Comment by iamdave210** [comment]
Discovered that it works properly immediately after clearing the cache. On subsequent loads (presumably from cache) is when it messes up.

**Comment by muzzwood** [comment]
Closing as this behaviour doesn't exist in the current version. Thanks!
