### ISSUE TITLE
Refresh Token error when trying to authenticate with Google

### ISSUE THREAD

**Issue by sonicpunk** [modmore/BigBrother#19]
MODX 2.5.1, Big Brother 1.3.0-pl

When I try to authorize the app with Google, I paste the auth code into the CMP and I get a spinning Loading graphic that goes for hours on end.

In the MODX Error Log I find this:
371) Error refreshing oAuth2 token: The 'refresh_token' parameter must be defined for the refresh token grant type

**Comment by Mark-H** [comment]
Sounds like it may not have saved the refresh token, if still consistently happening please provide more detail
