### ISSUE TITLE
Big Brother Displaying Blank

### ISSUE THREAD

**Issue by nickff** [modmore/BigBrother#21]
Starting today, all of my BigBrother installs are displaying blank. 

I'm assuming this is due to an update on Google's side and there will be a forthcoming update to the extra, but let me know!

**Comment by Mark-H** [comment]
This is news to me, so additional information would be appreciated.

**Comment by nickff** [comment]
Hmm...seems that I just needed to revoke authorization and re-authenticate. Apologies.

**Comment by funkyduke** [comment]
idd, I have this on regular base. I don't know the reason. I have to revoke and re-authenticate. The message is: `{"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}`

**Comment by Mark-H** [comment]
I've not seen this happen myself so I don't have a fix or an idea where to look for one.

**Comment by Mark-H** [comment]
Thinking out loud, if this is related to #19 perhaps there's an issue where google requires a new permission (refresh_token) during the initial authentication which it didn't require before, and because of that it only affects more recent installations.

**Comment by funkyduke** [comment]
#19 could be, I already had this also. And now that you say this, my oldest websites are the ones with the least problems.

**Comment by funkyduke** [comment]
This is in the log: 

`[2017-01-14 15:24:26] (ERROR @ /website_name/www/core/components/bigbrother/model/bigbrother/bigbrother.class.php : 381) Could not refresh access token!`

**Comment by crimsonpixel** [comment]
Just installed latest version on a new site and I'm getting the same error at @funkyduke in my logs.

**Comment by crimsonpixel** [comment]
For me the problem turned out to be incorrect assets path - so now all good...

**Comment by Mark-H** [comment]
@crimsonpixel Was that path something you set or something in big brother that was incorrect?

**Comment by crimsonpixel** [comment]
@Mark-H typo on my part. Nothing to do with Big Brother.

**Comment by Mark-H** [comment]
I'm assuming this is not still a recurring thing so closing.
