### ISSUE TITLE
full translation

### ISSUE THREAD

**Issue by sutrah** [modmore/BigBrother#24]
I would like to translate the days of the week and month. How can i do that ?
![tespt](https://cloud.githubusercontent.com/assets/3111077/24298131/5a72d122-10a5-11e7-9c79-d392889f938d.jpg)

**Comment by Mark-H** [comment]
I'm not immediately sure where that is coming from.. I don't think it's in the [lexicons](https://github.com/modmore/BigBrother/tree/master/core/components/bigbrother/lexicon). Will need to investigate.
