### ISSUE TITLE
You do not have permission to do this operation. Please contact the site administrator.

### ISSUE THREAD

**Issue by himurovich** [modmore/BigBrother#25]
I see that right after installation, for default admin, honestly I don't understand what (and why) additional permissions admin should have for workable extra, please help. 

![google analytics _ - google chrome 2017-05-23 10 40 38](https://cloud.githubusercontent.com/assets/2815640/26343316/20fb2114-3fa4-11e7-83f3-dd58ab877626.png)

Version: MODX Cloud 2.5.5-pl

**Comment by Mark-H** [comment]
That error seems to be shown if the user is not in the administrator user group, or whatever user groups you have defined in the admin_groups setting. I've not seen that error before.

**Comment by himurovich** [comment]
Thanks Mark, I've updated bigbrother.admin_groups with default admin group value, cleared cache, flushed permissions, relogged in but unfortunately I still have the same message. 

![system settings _ - google chrome 2017-05-25 07 34 55](https://cloud.githubusercontent.com/assets/2815640/26436126/f6dda9cc-411c-11e7-8c70-0f6c458c3d63.png)
![user_ - google chrome 2017-05-25 07 37 53](https://cloud.githubusercontent.com/assets/2815640/26436127/f6e002d0-411c-11e7-8713-c8cbff886b96.png)
![user_ _ aontas - google chrome 2017-05-25 07 38 45](https://cloud.githubusercontent.com/assets/2815640/26436125/f6db3dae-411c-11e7-831a-6e6f798f69e7.png)

**Comment by himurovich** [comment]
My bad, administrator group should be string, not ID. Issue may be closed, thanks again! 
![system settings _ - google chrome 2017-05-25 08 55 50](https://cloud.githubusercontent.com/assets/2815640/26437793/ddc630ca-4127-11e7-913c-2b4e69a35b86.png)
