### ISSUE TITLE
Numbers are gone

### ISSUE THREAD

**Issue by funkyduke** [modmore/BigBrother#26]
Since a couple of weeks the numbers aren't displayed anymore. I have it on all my websites.

**Comment by Mark-H** [comment]
Works fine here. 

What changed a couple of weeks ago? Did you install an adblocker, change your google password, or installed something in MODX?

**Comment by funkyduke** [comment]
No, didn't do anything strange. The graphics are showing correctly, but the numbers are gone. 

I have tested in different browsers on different computers (windows 10). Versions of Modx are different, lowest is 2.5.4.

**Comment by Mark-H** [comment]
Could you share a screenshot of what numbers you mean exactly that are missing? And check the browser dev tools (js console) and modx error log for any logged issues?

**Comment by funkyduke** [comment]
![screenshot_6](https://user-images.githubusercontent.com/1769979/28037595-1ffbb2d6-65bc-11e7-914c-93320134e984.jpg)

**Comment by funkyduke** [comment]
not on all websites, but here's an error I found.

(ERROR @ /website/www/core/components/bigbrother/processors/mgr/report/pie.class.php : 63) PHP warning: Invalid argument supplied for foreach()

**Comment by funkyduke** [comment]
I have testen it on my Ipad and also there the numbers are gone, so it's not related to win10.

**Comment by Mark-H** [comment]
Your screenshot looks similar to what I'm seeing... the numbers show on hover tho. That line seems to indicate it's not getting rows data https://github.com/modmore/BigBrother/blob/master/core/components/bigbrother/processors/mgr/report/pie.class.php#L63

**Comment by funkyduke** [comment]
Hmmm, in the past there were big (black) numbers under the graphics, these are gone.

**Comment by Mark-H** [comment]
I had to look up an [old screenshot](http://modx.s3.amazonaws.com/extras/4ee1102bf245544041000003/bigbrother-scr.png) to figure out what big numbers you meant, but you're right, those seem to have vanished!

**Comment by Mark-H** [comment]
It appears one of the metrics we were loading had been deprecated a while ago. They must've recently been removed.
