### ISSUE TITLE
Incorrect assets path under namespace

### ISSUE THREAD

**Issue by hugopeek** [modmore/BigBrother#28]
After package installation, it points to:

`/Users/mhamstra/Sites/premium.local/BigBrother/assets/components/bigbrother/`

Is this your way of spying on us, mhamstra? ;)

**Comment by Mark-H** [comment]
That path isn't actually used anywhere, but [pretty easy to fix](https://github.com/modmore/ClientConfig/commit/eaffe5375b2935a513b04c38ff5b9d4c029eb70f) ;)

If I were spying on you, it wouldn't be so easy to spot 😈
