### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by funkyduke** [modmore/BigBrother#29]
Since a couple of days I notice an error in the log file, don't know if it's important. I have this with several websites. Plugins & Modx up-to-date.

(ERROR @ /core/xpdo/cache/xpdocachemanager.class.php : 1039) PHP warning: filesize(): stat failed for /core/cache/bigbrother/access_token.cache.php

**Comment by Mark-H** [comment]
That's a php warning which only gets logged if you've changed your log_level setting. Can't hurt to prevent it from getting logged, but it probably doesn't hurt the actual functioning of the plugin.

**Comment by funkyduke** [comment]
Thx. Could it be that this happens when using SiteDash? I think this happens when I installed dashclient.

**Comment by Mark-H** [comment]
I'm not seeing anything in the sitedash client that lowers the log level, so that seems unlikely..

**Comment by Mark-H** [comment]
sizeof was separately reported in #31. Can't reproduce the error from this issue.
