### ISSUE TITLE
BigBrother connector.php throws a lot of errors

### ISSUE THREAD

**Issue by gadgetto** [modmore/BigBrother#3]
```
[2015-05-20 16:57:08] (ERROR @ /assets/components/bigbrother/connector.php) Array
(
    [result] => Array
        (
            [access_token] => xxx.yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy (original token removed)
            [token_type] => Bearer
            [expires_in] => 3600
        )

    [code] => 200
    [content_type] => application/json; charset=utf-8
)
```

**Comment by Mark-H** [comment]
Ah, debugging statement.  https://github.com/modmore/BigBrother/blob/master/core/components/bigbrother/model/bigbrother/bigbrother.class.php#L383

How often are you seeing that though? Refreshing the token should only happen about once an hour.

**Comment by gadgetto** [comment]
The error log entry happens every 10-30 seconds

**Comment by gadgetto** [comment]
It seems the continuos entries happens if I load the MODX Dashboard or the Analytics details page. Every page reload throws about 10-20 error entries.

**Comment by Mark-H** [comment]
Fixed in 789eb995c10214fe2611f3ada8f8174c7e2b3e00, nice catch :)

**Comment by gadgetto** [comment]
Hmm... can't find the fix Mark

**Comment by Mark-H** [comment]
Sorry, hadn't pushed yet, here you go: https://github.com/modmore/BigBrother/commit/789eb995c10214fe2611f3ada8f8174c7e2b3e00
