### ISSUE TITLE
Update action based routing (2.7)

### ISSUE THREAD

**Issue by Mark-H** [modmore/BigBrother#30]
2.7 is now logging deprecated notices for modAction-based routing. Needs to be updated to namespace based.

**Comment by greyskymedia** [comment]
is this why I can't install it on a site I just migrated?

```[2019-05-29 10:45:20] (ERROR in modProcessor::run @ /var/www/site/core/model/modx/modprocessor.class.php : 177) Flat file processor support, used for action authenticate/verifyPrerequisite with path /var/www/site/core/components/bigbrother/processors/mgr/authenticate/verifyprerequisite.php, is deprecated since version 2.7.0. ```

**Comment by Mark-H** [comment]
No that's just a warning for a feature that will be removed.

**Comment by greyskymedia** [comment]
bah

**Comment by Mark-H** [comment]
If you're having installation issues, posting the installation log in a new issue or post on the forum would be a great first step for getting help with that. ;)
