### ISSUE TITLE
Latest BigBrother Update uncaught error 

### ISSUE THREAD

**Issue by sonicpunk** [modmore/BigBrother#35]
Installed the BigBrother Update 1.4.0 in a 2.7.3 MODX installation. Upon trying to view the BigBrother app, I get the following error in the web browser:

Fatal error: Uncaught Error: Class 'IndexManagerController' not found in /model/modx/modmanagerresponse.class.php:190 Stack trace: #0
model/modx/modmanagerresponse.class.php(78): modManagerResponse->instantiateController('IndexManagerCon...', 'getInstanceDepr...') #1

modx/index.php(59): modManagerRequest->handleRequest() #4 {main} thrown in /model/modx/modmanagerresponse.class.php on line 190

PHP Version 7.3.6

**Comment by Mark-H** [comment]
Try using `?a=report&namespace=bigbrother` for the URL - I upgraded to namespace based routing but must've forgotten to enable upgrading the menu item. Will fix that in the next few days.

**Comment by Mark-H** [comment]
I've updated some broken links in the code for v1.4.1 but as I'm going through the review process with Google at the moment I'd like to wait to see if they have more issues that need to be resolved.

**Comment by Mark-H** [comment]
This was fixed in 1.4.1
