### ISSUE TITLE
bigbrother.class.php : 401 PHP warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by gadgetto** [modmore/BigBrother#37]
When visiting "Full report" (Vollständiger Bericht) page, I get these errors in log:

(ERROR @ /var/www/km/wwwRoot/core/components/bigbrother/model/bigbrother/bigbrother.class.php : 401) PHP warning: count(): Parameter must be an array or an object that implements Countable

BigBrother 1.4.1-pl
MODX 2.7.3-pl
PHP 7.3

**Comment by wfoojjaec** [comment]
Made a PR with a fix I keep using:
https://github.com/modmore/BigBrother/pull/38

**Comment by Mark-H** [comment]
Fixed in https://github.com/modmore/BigBrother/commit/098981bf2075dd1ff05b805d0d3c0abcbccc73a9 which will be in v1.5 - thanks.
