### ISSUE TITLE
Another chart library migration idea

### ISSUE THREAD

**Issue by wfoojjaec** [modmore/BigBrother#39]
Just a proposal, but it might be good to change a rendering library.
https://www.chartjs.org/
https://github.com/chartjs/Chart.js

I used this library for some drop-in charts for a MODX website. And it did go well.
But my main reason was - this will allow to avoid any license issues on commercial websites, because Chart.js is MIT.

**Comment by Mark-H** [comment]
In v2 we've indeed migrated to chart.js.
