### ISSUE TITLE
Big Brother dashboard panel is not work

### ISSUE THREAD

**Issue by zhdanovartur** [modmore/BigBrother#4]
Panel collapsed. And after reload I have JS-error:
"VM7589:1 Uncaught SyntaxError: Unexpected identifier"
and file:
```js
tpl.compiled = function(values, parent, xindex, xcount){ return ['<h3>',(values['title'] === undefined ? '' : values['title']),'<span>',(values['date_begin'] === undefined ? '' : values['date_begin']),' - ',(values['date_end'] === undefined ? '' : values['date_end']),'</span></h3><div class="account-infos"><button onclick="Ext.getCmp(\\'modx-panel-bigbrother\\').redirect(); return false;" class="inline-button green">Детальный отчёт</button>',(values['name'] === undefined ? '' : values['name']),'<span>',(values['id'] === undefined ? '' : values['id']),'</span></div>'].join('');};
```
![2015-05-23 18 43 29](https://cloud.githubusercontent.com/assets/1068224/7784809/df45c4ee-017b-11e5-93d7-31c6166d5c04.png)

**Comment by Mark-H** [comment]
Does it work after clearing your browser cache?

**Comment by zhdanovartur** [comment]
Sure)

**Comment by zhdanovartur** [comment]
Safari trace:
![2015-05-28 10 38 48](https://cloud.githubusercontent.com/assets/1068224/7854873/e45eceb4-0525-11e5-8cde-f597c6390eef.png)

**Comment by zhdanovartur** [comment]
Any news?(

**Comment by Mark-H** [comment]
Hi @zhdanovartur I've not been able of replicating this issue, not quite sure what is behind this :/
