### ISSUE TITLE
New Google Analytics (GA4) not supported

### ISSUE THREAD

**Issue by funkyduke** [modmore/BigBrother#40]
The Google Analytics (versie 4) has changed to a new stream. Since this new stream (platform) I cannot longer select the client in bigbrother Modx. The user is not in the list.

Modx 2.8.1. Latest version BigBrother

**Comment by travisbotello** [comment]
Experiencing the same problem with the new universal GA.

**Comment by Mark-H** [comment]
Just to confirm, GA4 is not currently supported. 

I'm planning to do a crowdfunding campaign to raise funds to rebuild the package and to add some cool new features to it, and will hopefully have that ready to announce in the next few weeks with a detailed plan.

**Comment by Mark-H** [comment]
Just (soft-)launched the crowdfunding campaign for Big Brother v2 to support GA4 and MODX3: 

https://modmore.com/extras/bigbrother/crowdfunding/

There's also a new 2.x branch here on GitHub where the actual work will happen.

**Comment by sebastian-marinescu** [comment]
As I just stumbled upon this, and left a comment on the Google Analytics Dashboard Team https://github.com/Sterc/Analytics-dashboard-widget/issues/34

For anyone interested, one workaround is to create an old-school Universal Analytics property:
https://support.google.com/analytics/answer/10269537

**Comment by Mark-H** [comment]
BigBrother 2 is available with GA4 support and will be made the default on modx.com shortly.

We'll keep BigBrother v1.5 working for the time being (MODX2 only) for GA3/UA users. There's a compatibility matrix in the readme and on https://support.modmore.com/article/228-what-is-universal-analytics-google-analytics-4 to clarify when to use which versions.
