### ISSUE TITLE
[BB2] Add link on main widget to get to the authorize cmp?

### ISSUE THREAD

**Issue by Mark-H** [modmore/BigBrother#46]
There needs to be a way to get to the authorization cmp when the authorization is still valid, to allow revoking or changing accounts. Right now there isn't.

I can think of two options:

- Add a link somewhere inside the main widget, perhaps a cog icon in the title bar of sorts. 
- Add a link (modMenu) in the main MODX nav. Not sure if this should go into Extras as it's not necessarily something that needs to be accessed often, so perhaps in the settings or another menu.

**Comment by muzzwood** [comment]
Done!
