### ISSUE TITLE
[BB2] Show relevant period dates 

### ISSUE THREAD

**Issue by Mark-H** [modmore/BigBrother#49]
Per the sketch this was planned to go into the widget title. Due to some `overflow: hidden` that may be tricky to accomplish with html alone and require handling it with JS instead. Perhaps in the `reports` processor return the relevant dates and use `BigBrother.refreshCharts()` to inject that dynamically?

Doesn't look like we'll get close enough to the period selector to add that, so just static dates for the current and the previous period it is being compared to.

**Comment by muzzwood** [comment]
Done!
