### ISSUE TITLE
Dashboard Blank Upon Initial Load - Works Upon Browser Refresh

### ISSUE THREAD

**Issue by mikelannen** [modmore/BigBrother#5]
Upon initial load of the Big Brother Dashboard in MODX Manager, all of the boxes of stats are blank white. Then when you hit refresh in the browser, everything loads. This is happening on all sites that I have updated the Extra on and in the latest versions of Chrome/FF on Mac and on REVO 2.33-pl.

**Comment by hurby** [comment]
Same here, seen on several websites.

grtz
Hurby

**Comment by deyand** [comment]
Same here.
Also when you press on the View full report button everything loads.

**Comment by Mark-H** [comment]
I'm guessing it might be hitting some API quotas by firing off requests rapidly after each other..when refreshing, part of the results are cached so it can grab the others. 

I've just tripled the per second quotas on the standard app key.. maybe that'll help?

**Comment by mikelannen** [comment]
Thanks Mark! If that doesn't solve it, would it be helpful if we sent you the details from www.supportdetails.com to see if there are any common factors in versions of browsers that might be causing the issue? Or anything else you might need to help troubleshoot?

**Comment by mikelannen** [comment]
I think that did the trick Mark! After I logged out fully from my Manager sessions of the sites in question and then logged back in, it seems to load up perfectly each time now. Going to try it on a few more sites and will report back. I am guessing it might have been the quota issue.

**Comment by mikelannen** [comment]
I might have spoke to soon. All sites are now loading blank dashboard again upon initial load and then works upon refresh.

Is anyone else experiencing this again?

**Comment by deyand** [comment]
Yeah, the same situation here...

**Comment by Mark-H** [comment]
It looks like it might be related to the auth tokens; it seems to be throwing the following error on the failing requests:

> message: "{"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}"

Probably happens because it has to refresh the token, but in between refreshing the token, and sending the request, the token is invalidated again?

On a refresh, the auth key is still valid so it doesn't have to refresh, and it works fine.

Will need to look into a proper fix for this, hopefully this weekend.

**Comment by mikelannen** [comment]
You rock as always Mark!

On Fri, May 29, 2015 at 5:29 PM Mark Hamstra <notifications@github.com>
wrote:

> It looks like it might be related to the auth tokens; it seems to be
> throwing the following error on the failing requests:
>
> message:
> "{"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid
> Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid
> Credentials"}}"
>
> Probably happens because it has to refresh the token, but in between
> refreshing the token, and sending the request, the token is invalidated
> again?
>
> On a refresh, the auth key is still valid so it doesn't have to refresh,
> and it works fine.
>
> Will need to look into a proper fix for this, hopefully this weekend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modmore/BigBrother/issues/5#issuecomment-106940626>.
>
-- 

Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB <http://www.eternitymarketing.com/>

(802) 865-2000  x700

*We've Moved!*


182 Main Street
Studio 3
Burlington, VT 05401

**Comment by digitalpenguin** [comment]
Yes same problem here. Great to see I'm not the only one :)

**Comment by mikelannen** [comment]
Any update on this glitch?
On Fri, Jun 19, 2015 at 1:12 AM digitalpenguin <notifications@github.com>
wrote:

> Yes same problem here. Great to see I'm not the only one :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modmore/BigBrother/issues/5#issuecomment-113371557>.
>
-- 

Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB

(802) 865-2000  x700

182 Main Street
Studio 3
Burlington, VT 05401

**Comment by Mark-H** [comment]
Think I got this one sorted :) Sorry it took so long.

**Comment by digitalpenguin** [comment]
Fantastic! Thanks Mark
