### ISSUE TITLE
[BB2] handleState sometimes not updating panel after authorization or revoke

### ISSUE THREAD

**Issue by muzzwood** [modmore/BigBrother#52]
This happens intermittently. 
The success message will show but the page layout stays as it is.
Reloading the page shows the correct view.

It appears to be failing at this check:
https://github.com/modmore/BigBrother/blob/2.x/assets/components/bigbrother/mgr/authorize.panel.js#L283

**Comment by muzzwood** [comment]
Interestingly, this only appears to be an issue on my local dev environment...
It appears to be working perfectly on a remote server.

If anyone else comes across this issue, please leave a comment here.

**Comment by Mark-H** [comment]
Closing unless there's more reports/consistent way to reproduce.
