### ISSUE TITLE
v1 to v2 upgrade removes assigned widget entirely instead of replacing

### ISSUE THREAD

**Issue by Mark-H** [modmore/BigBrother#57]
[I added some logic to automatically migrate to v2](https://github.com/modmore/BigBrother/blob/2.x/_build/resolvers/upgrade.resolver.php#L47), but for some reason removing the $oldWidget is causing the widget placement to also be removed. This can be seen in the upgrade log (..which I didn't copy..) where it says:

- Replacing v1 widget with v2 widget on dashboard {id} 
- Removing  v1 widget
- (xpdo)Removing modDashboardWidgetPlacement with primary key {id}
- (xpdo)Removing modDashboardWidget with primary key

That third step is baffling me - it shouldn't be doing that as we just adjusted the widget placement to use a different widget. 

Will need to look into it some more or @muzzwood maybe you can spot what I'm overlooking. 

All I can think of is that perhaps the placement isn't saving the new widget because of some xPDO magic with related objects, but I tried to avoid getOne|Many/addOne|Many for that very reason..

**Comment by muzzwood** [comment]
It's a little long-winded but a work-around has been implemented by storing the placement values, removing the old placement, creating a new one and setting the values.
https://github.com/modmore/BigBrother/commit/7866b8e2777740962d0c94fcf9accbfd37cd4ddd

Looks good during testing on my end but I'll leave this open until you can test it too.
