### ISSUE TITLE
Lexicons not loading via JavaScript in reports

### ISSUE THREAD

**Issue by muzzwood** [modmore/BigBrother#59]
Lexicons are loading fine via PHP but when using the syntax `_('bigbrother.example')`, the lexicon isn't found.

An example of this is here:
https://github.com/modmore/BigBrother/blob/2.x/assets/components/bigbrother/mgr/reports/acquisition.js#L20

The same occurs in the visits chart (though apparently I missed converting that text to lexicons):
https://github.com/modmore/BigBrother/blob/2.x/assets/components/bigbrother/mgr/reports/visits.js#L18

Lexicons loaded (specifically dashboard.inc.php) via the widget configuration page, seem to be loaded for widget names and descriptions (when configuring which widgets to use on a dashboard), but doesn't have bearing on the lexicons within the widget.

**Comment by Mark-H** [comment]
I did merge the lexicons earlier so it's possible I missed a reference somewhere, or that you need to run the bootstrap again to fix some references..

**Comment by muzzwood** [comment]
Oh yeah I saw that, nice one! (I should have said default.inc.php rather than dashboard.inc.php)

Unfortunately, they don't seem to be resolving for me at least despite rebuilding, deleting cache etc.

![Screenshot from 2021-06-08 12-05-07](https://user-images.githubusercontent.com/5160368/121121444-29420c80-c852-11eb-9990-6a0623fd92a5.png)

**Comment by Mark-H** [comment]
Can confirm those lexicons are missing

**Comment by Mark-H** [comment]
Looks like v1 manually added the lexicons:

https://github.com/modmore/BigBrother/blob/3a0aa40bb2d27d6857573e53880945a47aa8e30f/core/components/bigbrother/controllers/widget.class.php#L54

Kinda feels like there should be a better way, though.

**Comment by muzzwood** [comment]
Interesting... 
If that works, perhaps that's a good short-term option at least

**Comment by muzzwood** [comment]
Now working due to applying the manual loading above.
