### ISSUE TITLE
Feature Request: Additional Reporting Options

### ISSUE THREAD

**Issue by mikelannen** [modmore/BigBrother#6]
Does anyone think there are additional reports that would be beneficial to show on the dashboard widget, and within the view full report?

Maybe we could put a list together of what our clients would like to see most in there and vote on them and create a donation round for Mark to implement them if he has the time?

Thoughts?

**Comment by Mark-H** [comment]
Not everything requires a donation round (though, when offered, my Dutch instincts are quick to point to a paypal form :P), but if there are any reports that would be worth adding I would be more than happy to see what I can do. Just open a fresh issue for every unique report with details.
