### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by funkyduke** [modmore/BigBrother#74]
When I try to sign in with Google, I get the following error:

Fout bij autorisatie
Fout 400: redirect_uri_mismatch
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type.

I have followed the instructions on https://docs.modmore.com/en/Open_Source/BigBrother/Custom_oAuth_Credentials.html

**Comment by Mark-H** [comment]
>  The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type.

That means you're using the wrong credential type. Maybe they renamed the types and the documentation needs to be updated, but looking at my account it should be oAuth Client ID > Desktop app.

**Comment by funkyduke** [comment]
That's it. Thank you. The docs say "For the Type, choose webapplication.", so that must be Desktop app instead.

**Comment by Mark-H** [comment]
They don't say that if you refresh the page. ;)
