### ISSUE TITLE
Empty list of accounts to choose from

### ISSUE THREAD

**Issue by rthrash** [modmore/BigBrother#8]
On the latest rc3 release, I authenticated to my account but I am not able to see any accounts from which to choose. I have access to about a dozen different accounts.

**Comment by Mark-H** [comment]
Sometimes trying to open it a second time makes it render properly, or because you have so many accounts it may take longer to load than expected. It worked fine with the few dozen _profiles_ I've got access to... 

Maybe try re-authenticating?
